/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aurora_soundtouch_Jni */

#ifndef _Included_com_aurora_soundtouch_Jni
#define _Included_com_aurora_soundtouch_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aurora_soundtouch_Jni
 * Method:    getCInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aurora_soundtouch_Jni_getCInt
  (JNIEnv *, jobject);

/*
 * Class:     com_aurora_soundtouch_Jni
 * Method:    getCString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aurora_soundtouch_Jni_getCString
  (JNIEnv *, jobject);

/*
 * Class:     com_aurora_soundtouch_Jni
 * Method:    setWAV
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aurora_soundtouch_Jni_setWAV
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
